name: Publish to pages
on:
    push:
        branches: [main]
jobs:
    build_vue:
        runs-on: ubuntu-latest
        name: Build Vue
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - id: Build-Vue
              uses: xRealNeon/VuePagesAction@1.0.1
              with:
                  username: 'yvo-niedrich'
                  reponame: 'markdown-blog'
                  token: ${{ secrets.GITHUB_TOKEN }}
